#!/bin/bash
# =============================================================================
# HW6 shared configuration helpers
# Network: 192.168.0.<D>  (A.B.C fixed; only last octet is prompted)
# Run all setup scripts as root.
# =============================================================================

HW6_NETWORK_PREFIX="${HW6_NETWORK_PREFIX:-192.168.0}"
HW6_SUBNET="${HW6_SUBNET:-192.168.0.0/24}"
HW6_CONFIG_DIR="${HW6_CONFIG_DIR:-/etc/hw6}"
HW6_CONFIG_FILE="${HW6_CONFIG_FILE:-${HW6_CONFIG_DIR}/cluster.conf}"
HW6_NFS_DIR="${HW6_NFS_DIR:-/var/lib/libvirt/images}"
HW6_NFS_CONFIG_PATH="${HW6_NFS_DIR}/hw6/cluster.conf"
HW6_NFS_KEYS_DIR="${HW6_NFS_DIR}/hw6/keys"
HW6_SSH_KNOWN_HOSTS="${HW6_CONFIG_DIR}/ssh_known_hosts"
HW6_CPU_CAP="${HW6_CPU_CAP:-8}"
HW6_MEM_CAP_MB="${HW6_MEM_CAP_MB:-16384}"
HW6_HOST_DOMAIN="${HW6_HOST_DOMAIN:-hw6.local}"
HW6_HOSTS_MARK_BEGIN="# BEGIN HW6 CLUSTER"
HW6_HOSTS_MARK_END="# END HW6 CLUSTER"
HW6_CLUSTER_HOSTS=(servera serverb serverc)

HOST_A_IP=""
HOST_B_IP=""
HOST_C_IP=""
HOST_A_D=""
HOST_B_D=""
HOST_C_D=""

# Callbacks set by setup_*.sh
ok_cb()  { echo "  OK: $*"; }
warn_cb() { echo "  WARN: $*"; }

hw6_require_root() {
    if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
        echo "ERROR: Run as root:  sudo bash $0"
        exit 1
    fi
}

hw6_ip_from_d() {
    echo "${HW6_NETWORK_PREFIX}.$1"
}

hw6_validate_d() {
    local d="$1"
    [[ "$d" =~ ^[0-9]+$ ]] || return 1
    (( d >= 1 && d <= 254 )) || return 1
    return 0
}

hw6_prompt_d() {
    local label="$1"
    local varname="$2"
    local value=""

    while true; do
        read -r -p "  ${label} last octet (1-254, network ${HW6_NETWORK_PREFIX}.?): " value
        value="${value// /}"
        if hw6_validate_d "$value"; then
            printf -v "$varname" '%s' "$value"
            return 0
        fi
        echo "    Invalid: enter a number from 1 to 254."
    done
}

hw6_prompt_cluster_config() {
    echo ""
    echo "  Cluster IPs use fixed prefix: ${HW6_NETWORK_PREFIX}.<D>"
    echo "  Enter the last octet (D) for each host (no defaults)."
    echo ""

    hw6_prompt_d "Host-A (servera)" HOST_A_D
    hw6_prompt_d "Host-B (serverb)" HOST_B_D
    hw6_prompt_d "Host-C (serverc)" HOST_C_D

    if [[ "$HOST_A_D" == "$HOST_B_D" || "$HOST_A_D" == "$HOST_C_D" || "$HOST_B_D" == "$HOST_C_D" ]]; then
        echo "  Error: Host-A, B, and C must use different last octets."
        return 1
    fi

    HOST_A_IP="$(hw6_ip_from_d "$HOST_A_D")"
    HOST_B_IP="$(hw6_ip_from_d "$HOST_B_D")"
    HOST_C_IP="$(hw6_ip_from_d "$HOST_C_D")"
    return 0
}

hw6_write_config() {
    mkdir -p "$HW6_CONFIG_DIR"
    mkdir -p "$(dirname "$HW6_NFS_CONFIG_PATH")"
    mkdir -p "$HW6_NFS_KEYS_DIR"

    cat > "$HW6_CONFIG_FILE" << EOF
# HW6 cluster configuration (generated by setup)
NETWORK_PREFIX=${HW6_NETWORK_PREFIX}
SUBNET=${HW6_SUBNET}
HOST_A_IP=${HOST_A_IP}
HOST_B_IP=${HOST_B_IP}
HOST_C_IP=${HOST_C_IP}
HOST_A_D=${HOST_A_D}
HOST_B_D=${HOST_B_D}
HOST_C_D=${HOST_C_D}
NFS_DIR=${HW6_NFS_DIR}
CPU_CAP=${HW6_CPU_CAP}
MEM_CAP_MB=${HW6_MEM_CAP_MB}
HOST_DOMAIN=${HW6_HOST_DOMAIN}
EOF

    chmod 644 "$HW6_CONFIG_FILE"

    if [[ -d "$HW6_NFS_DIR" ]]; then
        cp -f "$HW6_CONFIG_FILE" "$HW6_NFS_CONFIG_PATH"
        chmod 644 "$HW6_NFS_CONFIG_PATH"
    fi
}

hw6_load_config() {
    local file="$1"
    [[ -f "$file" ]] || return 1
    # shellcheck disable=SC1090
    source "$file"
    [[ -n "${HOST_DOMAIN:-}" ]] && HW6_HOST_DOMAIN="$HOST_DOMAIN"
    [[ -n "$HOST_A_IP" && -n "$HOST_B_IP" && -n "$HOST_C_IP" ]] || return 1
    return 0
}

hw6_migrate_dest_uri() {
    echo "qemu+ssh://root@$(hw6_fqdn "$1")/system"
}

hw6_ensure_config() {
    local mode="${1:-prompt}"

    if [[ -f "$HW6_CONFIG_FILE" ]] && hw6_load_config "$HW6_CONFIG_FILE"; then
        echo ""
        echo "  Existing config: $HW6_CONFIG_FILE"
        echo "    Host-A (servera): $HOST_A_IP"
        echo "    Host-B (serverb): $HOST_B_IP"
        echo "    Host-C (serverc): $HOST_C_IP"
        echo ""
        read -r -p "  Use this config? [Y/n] " reuse
        if [[ ! "$reuse" =~ ^[Nn]$ ]]; then
            return 0
        fi
    fi

    if [[ "$mode" == "load_only" ]]; then
        return 1
    fi

    while true; do
        hw6_prompt_cluster_config || continue
        echo ""
        echo "  Summary:"
        echo "    Host-A (servera): $HOST_A_IP"
        echo "    Host-B (serverb): $HOST_B_IP"
        echo "    Host-C (serverc): $HOST_C_IP"
        echo "    Subnet (NFS):     $HW6_SUBNET"
        echo ""
        read -r -p "  Write config and continue? [y/N] " confirm
        if [[ "$confirm" =~ ^[Yy]$ ]]; then
            hw6_write_config
            return 0
        fi
        echo "  Re-enter host addresses."
    done
}

hw6_ensure_config_from_nfs() {
    if [[ -f "$HW6_CONFIG_FILE" ]] && hw6_load_config "$HW6_CONFIG_FILE"; then
        return 0
    fi
    if [[ -f "$HW6_NFS_CONFIG_PATH" ]] && hw6_load_config "$HW6_NFS_CONFIG_PATH"; then
        hw6_write_config
        return 0
    fi
    return 1
}

hw6_fqdn() {
    echo "${1}.${HW6_HOST_DOMAIN}"
}

# 127.0.0.1 must not map the cluster hostname (breaks live migration on libvirt 9+)
hw6_fix_loopback_hosts() {
    local hf="/etc/hosts"
    if grep -q '^127\.0\.0\.1' "$hf"; then
        sed -i 's/^127\.0\.0\.1.*/127.0.0.1   localhost localhost.localdomain localhost4/' "$hf"
    else
        echo '127.0.0.1   localhost localhost.localdomain localhost4' >> "$hf"
    fi
    if grep -q '^::1' "$hf"; then
        sed -i 's/^::1.*/::1         localhost localhost.localdomain localhost6/' "$hf"
    else
        echo '::1         localhost localhost.localdomain localhost6' >> "$hf"
    fi
}

# Replace or inject managed /etc/hosts block (idempotent, with FQDN)
hw6_hosts_inject() {
    local hf="/etc/hosts"
    local tmp
    local domain="${HW6_HOST_DOMAIN}"
    tmp="$(mktemp)"

    if grep -qF "$HW6_HOSTS_MARK_BEGIN" "$hf" 2>/dev/null; then
        awk -v b="$HW6_HOSTS_MARK_BEGIN" -v e="$HW6_HOSTS_MARK_END" '
            $0 == b { skip=1; next }
            $0 == e { skip=0; next }
            !skip { print }
        ' "$hf" > "$tmp"
    else
        cp "$hf" "$tmp"
    fi

    {
        cat "$tmp"
        echo ""
        echo "$HW6_HOSTS_MARK_BEGIN"
        printf '%s\t%s %s\n' "$HOST_A_IP" "servera.${domain}" "servera"
        printf '%s\t%s %s\n' "$HOST_B_IP" "serverb.${domain}" "serverb"
        printf '%s\t%s %s\n' "$HOST_C_IP" "serverc.${domain}" "serverc"
        echo "$HW6_HOSTS_MARK_END"
    } > "${tmp}.new"

    install -m 644 "${tmp}.new" "$hf"
    rm -f "$tmp" "${tmp}.new"
    ok_cb "/etc/hosts updated (FQDN *.${domain})"
}

# Set this machine's hostname + cluster /etc/hosts (required for virsh migrate)
hw6_configure_cluster_hostname() {
    local short="$1"
    local fqdn

    case "$short" in
        servera|serverb|serverc) ;;
        *) warn_cb "Unknown host role: $short"; return 1 ;;
    esac

    fqdn="$(hw6_fqdn "$short")"
    hostnamectl set-hostname "$fqdn" 2>/dev/null || echo "$fqdn" > /etc/hostname

    hw6_fix_loopback_hosts
    hw6_hosts_inject

    ok_cb "Hostname: $(hostname -f) (migration FQDN)"
}

hw6_update_hosts_file() {
    hw6_hosts_inject
}

# Auto-detect Host-B vs Host-C from configured IPs on this machine
hw6_detect_sub_role() {
    local ip
    THIS_ROLE=""
    THIS_IP=""

    for ip in $(hostname -I 2>/dev/null); do
        if [[ "$ip" == "$HOST_B_IP" ]]; then
            THIS_ROLE="b"
            THIS_IP="$HOST_B_IP"
            return 0
        fi
        if [[ "$ip" == "$HOST_C_IP" ]]; then
            THIS_ROLE="c"
            THIS_IP="$HOST_C_IP"
            return 0
        fi
    done
    return 1
}

hw6_prompt_sub_role() {
    echo ""
    echo "  Could not detect role from NIC addresses."
    echo "    b = Host-B (serverb) → ${HOST_B_IP}"
    echo "    c = Host-C (serverc) → ${HOST_C_IP}"
    echo ""
    while true; do
        read -r -p "  Enter b or c: " THIS_ROLE
        THIS_ROLE="${THIS_ROLE,,}"
        case "$THIS_ROLE" in
            b) THIS_IP="$HOST_B_IP"; return 0 ;;
            c) THIS_IP="$HOST_C_IP"; return 0 ;;
            *) echo "    Enter b or c." ;;
        esac
    done
}

hw6_role_to_hostname() {
    case "$1" in
        a|A|servera) echo "servera" ;;
        b|B|serverb) echo "serverb" ;;
        c|C|serverc) echo "serverc" ;;
        *) return 1 ;;
    esac
}

hw6_install_openssh() {
    if ! rpm -q openssh-server openssh-clients &>/dev/null; then
        dnf install -y -q openssh-server openssh-clients
    fi
    systemctl enable --now sshd &>/dev/null || systemctl enable --now sshd.service
    ok_cb "sshd enabled"
}

# cloud-init ISO: Rocky 9/10 often has xorriso, not genisoimage / bridge-utils
hw6_install_iso_creator() {
    if command -v xorriso &>/dev/null || command -v genisoimage &>/dev/null; then
        return 0
    fi
    if dnf install -y -q xorriso &>/dev/null; then
        ok_cb "xorriso installed (cloud-init ISO)"
        return 0
    fi
    if dnf install -y -q genisoimage &>/dev/null; then
        ok_cb "genisoimage installed (cloud-init ISO)"
        return 0
    fi
    warn_cb "Install ISO tool manually: dnf install -y xorriso"
    return 1
}

hw6_make_cidata_iso() {
    local iso_path="$1"
    local user_data_file="$2"
    local meta_data_file="$3"

    if command -v genisoimage &>/dev/null; then
        genisoimage -quiet -output "$iso_path" -volid cidata -joliet -rock \
            "$user_data_file" "$meta_data_file"
        return $?
    fi
    if command -v xorriso &>/dev/null; then
        xorriso -as mkisofs -quiet -output "$iso_path" -volid cidata -joliet -rock \
            "$user_data_file" "$meta_data_file"
        return $?
    fi
    return 1
}

# Live migration (NFS shared qcow2 at /var/lib/libvirt/images on all hosts).
# libvirt 9+ may not treat NFS file disks as "shared" — --unsafe is required for this lab.
hw6_virsh_migrate_live() {
    local vm_name="$1"
    local dest_uri="$2"
    virsh migrate --live --persistent --undefinesource --unsafe \
        "$vm_name" "$dest_uri"
}

hw6_check_nfs_shared_storage() {
    local path="${1:-$HW6_NFS_DIR}"
    mount | grep -q " on ${path} " && return 0
    mount | grep -q "${path}" && return 0
    return 1
}

hw6_sshd_lab_config() {
    local dropin="/etc/ssh/sshd_config.d/99-hw6-lab.conf"
    cat > "$dropin" << 'EOF'
# HW6 lab — root SSH for KVM live migration orchestration
PermitRootLogin yes
PubkeyAuthentication yes
PasswordAuthentication yes
EOF
    chmod 644 "$dropin"
    systemctl reload sshd 2>/dev/null || systemctl restart sshd
    ok_cb "sshd lab config applied"
}

hw6_ssh_client_config() {
    local dropin="/etc/ssh/ssh_config.d/50-hw6-cluster.conf"
    mkdir -p "$HW6_CONFIG_DIR"
    touch "$HW6_SSH_KNOWN_HOSTS"
    chmod 644 "$HW6_SSH_KNOWN_HOSTS"

    cat > "$dropin" << EOF
# HW6 cluster SSH client defaults
Host servera serverb serverc ${HOST_A_IP} ${HOST_B_IP} ${HOST_C_IP}
    User root
    StrictHostKeyChecking accept-new
    UserKnownHostsFile ${HW6_SSH_KNOWN_HOSTS}
    GlobalKnownHostsFile /dev/null
EOF
    chmod 644 "$dropin"
}

hw6_ssh_prepare() {
    local ssh_dir="/root/.ssh"

    mkdir -p "$ssh_dir" "$HW6_NFS_KEYS_DIR"
    chmod 700 "$ssh_dir"

    if [[ ! -f "${ssh_dir}/id_rsa" ]]; then
        ssh-keygen -t rsa -b 4096 -N "" -f "${ssh_dir}/id_rsa" -q
        ok_cb "SSH key pair generated"
    else
        ok_cb "SSH key pair present"
    fi

    touch "${ssh_dir}/authorized_keys"
    chmod 600 "${ssh_dir}/authorized_keys"

    if ! grep -qF "$(cat "${ssh_dir}/id_rsa.pub")" "${ssh_dir}/authorized_keys" 2>/dev/null; then
        cat "${ssh_dir}/id_rsa.pub" >> "${ssh_dir}/authorized_keys"
    fi

    hw6_ssh_client_config
    hw6_sshd_lab_config
}

hw6_ssh_append_pubkey() {
    local pub_file="$1"
    local auth="/root/.ssh/authorized_keys"
    [[ -f "$pub_file" ]] || return 0
    if ! grep -qF "$(cat "$pub_file")" "$auth" 2>/dev/null; then
        cat "$pub_file" >> "$auth"
    fi
}

hw6_ssh_publish_key() {
    local hostname="$1"
    local pub="/root/.ssh/id_rsa.pub"
    local dest="${HW6_NFS_KEYS_DIR}/${hostname}.pub"

    [[ -f "$pub" ]] || return 1
    mkdir -p "$HW6_NFS_KEYS_DIR"
    install -m 644 "$pub" "$dest"
    ok_cb "Published ${hostname}.pub on NFS"
}

hw6_ssh_sync_keys_from_nfs() {
    local pub auth="/root/.ssh/authorized_keys"

    hw6_ssh_append_pubkey "/root/.ssh/id_rsa.pub"

    if [[ ! -d "$HW6_NFS_KEYS_DIR" ]]; then
        warn_cb "NFS keys dir missing: ${HW6_NFS_KEYS_DIR}"
        return 1
    fi

    shopt -s nullglob
    for pub in "${HW6_NFS_KEYS_DIR}"/*.pub; do
        hw6_ssh_append_pubkey "$pub"
    done
    shopt -u nullglob

    chmod 600 "$auth"
    ok_cb "Merged cluster public keys into authorized_keys"
}

hw6_ssh_update_known_hosts() {
    mkdir -p "$HW6_CONFIG_DIR"
    : > "$HW6_SSH_KNOWN_HOSTS"

    ssh-keyscan -H servera serverb serverc \
        "$HOST_A_IP" "$HOST_B_IP" "$HOST_C_IP" 2>/dev/null \
        >> "$HW6_SSH_KNOWN_HOSTS" || true

    chmod 644 "$HW6_SSH_KNOWN_HOSTS"
    ok_cb "ssh_known_hosts updated"
}

hw6_ssh_wait_for_port() {
    local host="$1"
    local port="${2:-22}"
    local timeout="${3:-120}"
    local elapsed=0

    while (( elapsed < timeout )); do
        if timeout 2 bash -c "echo >/dev/tcp/${host}/${port}" 2>/dev/null; then
            return 0
        fi
        sleep 3
        elapsed=$((elapsed + 3))
    done
    return 1
}

hw6_ssh_test_host() {
    local host="$1"
    ssh -o BatchMode=yes -o ConnectTimeout=8 \
        "root@${host}" "virsh version" &>/dev/null
}

hw6_ssh_try_password_install() {
    local target_host="$1"
    local password="${HW6_ROOT_PASSWORD:-}"

    [[ -n "$password" ]] || return 1

    if ! command -v sshpass &>/dev/null; then
        dnf install -y -q sshpass 2>/dev/null || return 1
    fi

    sshpass -p "$password" ssh-copy-id -o StrictHostKeyChecking=accept-new \
        -i /root/.ssh/id_rsa.pub "root@${target_host}" &>/dev/null
}

hw6_ssh_setup_sub() {
    local role_hostname="$1"

    hw6_install_openssh
    hw6_ssh_prepare
    hw6_ssh_publish_key "$role_hostname"
    hw6_ssh_sync_keys_from_nfs
    hw6_ssh_update_known_hosts
}

hw6_ssh_wait_for_nfs_keys() {
    local need=("$@")
    local timeout="${HW6_SSH_WAIT_TIMEOUT:-300}"
    local elapsed=0
    local missing key

    while (( elapsed < timeout )); do
        missing=()
        for key in "${need[@]}"; do
            [[ -f "${HW6_NFS_KEYS_DIR}/${key}.pub" ]] || missing+=("$key")
        done
        if ((${#missing[@]} == 0)); then
            return 0
        fi
        echo "  Waiting for NFS keys: $(printf '%s.pub ' "${missing[@]}")(${elapsed}s / ${timeout}s)"
        echo "  → Run setup_sub.sh on the missing host(s)."
        sleep 5
        elapsed=$((elapsed + 5))
    done
    return 1
}

hw6_ssh_setup_main_peers() {
  hw6_ssh_sync_keys_from_nfs
  hw6_ssh_update_known_hosts

  local peer host

  for peer in serverb serverc; do
      host="$peer"
      if ! hw6_ssh_wait_for_port "$host" 22 30; then
          warn_cb "SSH port not open on ${host} — skip test"
          continue
      fi
      if hw6_ssh_test_host "$host"; then
          ok_cb "Passwordless SSH to ${host} OK"
      else
          if hw6_ssh_try_password_install "$host"; then
              ok_cb "Installed key on ${host} via HW6_ROOT_PASSWORD"
          else
              warn_cb "Cannot SSH to ${host} yet — finish setup_sub or set HW6_ROOT_PASSWORD"
          fi
      fi
  done
}

hw6_ssh_setup_main_finalize() {
    hw6_install_openssh
    hw6_ssh_prepare
    hw6_ssh_publish_key "servera"

    if [[ "${HW6_SKIP_SSH_WAIT:-0}" == "1" ]]; then
        warn_cb "HW6_SKIP_SSH_WAIT=1 — skipping wait for Host-B/C keys"
        hw6_ssh_setup_main_peers
        return 0
    fi

    echo ""
    echo "  Waiting for Host-B/C to publish SSH keys (setup_sub.sh)..."
    if hw6_ssh_wait_for_nfs_keys serverb serverc; then
        hw6_ssh_setup_main_peers
    else
        warn_cb "Timed out — run on Host-A after B/C setup:"
        warn_cb "  hw6_ssh_sync_keys_from_nfs && hw6_ssh_update_known_hosts"
        warn_cb "Or re-run: bash setup_main.sh (use existing config)"
    fi
}
