#!/bin/bash
# =============================================================================
# HW6 shared configuration helpers
# Network: 192.168.0.<D>  (A.B.C fixed; only last octet is prompted)
# Run all setup scripts as root.
# =============================================================================

HW6_NETWORK_PREFIX="${HW6_NETWORK_PREFIX:-192.168.0}"
HW6_SUBNET="${HW6_SUBNET:-192.168.0.0/24}"
HW6_CONFIG_DIR="${HW6_CONFIG_DIR:-/etc/hw6}"
HW6_CONFIG_FILE="${HW6_CONFIG_FILE:-${HW6_CONFIG_DIR}/cluster.conf}"
HW6_NFS_DIR="${HW6_NFS_DIR:-/var/lib/libvirt/images}"
HW6_NFS_CONFIG_PATH="${HW6_NFS_DIR}/hw6/cluster.conf"
HW6_NFS_KEYS_DIR="${HW6_NFS_DIR}/hw6/keys"
HW6_SSH_KNOWN_HOSTS="${HW6_CONFIG_DIR}/ssh_known_hosts"
HW6_CPU_CAP="${HW6_CPU_CAP:-8}"
HW6_MEM_CAP_MB="${HW6_MEM_CAP_MB:-16384}"
HW6_HOST_DOMAIN="${HW6_HOST_DOMAIN:-hw6.local}"
# cloud-init ISOs stay off NFS — avoids "Resource temporarily unavailable" when B/C hold locks
HW6_CLOUD_INIT_DIR="${HW6_CLOUD_INIT_DIR:-/var/tmp/hw6-cloud-init}"
# Same CPU on A/B/C — host-model breaks migration; Intel cluster must not require AMD SVM
HW6_VM_CPU_MODEL="${HW6_VM_CPU_MODEL:-qemu64}"
# Disable AMD-V (svm): all hosts are Intel i7 — "Host CPU does not provide svm" on Host-C otherwise
HW6_VM_CPU_FLAGS="${HW6_VM_CPU_FLAGS:--svm}"
HW6_VM_MACHINE="${HW6_VM_MACHINE:-q35}"

# virt-install / virt-xml CPU string, e.g. qemu64,-svm
hw6_vm_cpu_spec() {
    local spec="${HW6_VM_CPU_MODEL}"
    [[ -n "${HW6_VM_CPU_FLAGS}" ]] && spec="${spec},${HW6_VM_CPU_FLAGS}"
    echo "$spec"
}

# True if domain XML already matches lab CPU (skip slow virt-xml / SSH loops)
hw6_vm_cpu_ok() {
    local vm="$1"
    local xml

    xml="$(virsh dumpxml "$vm" 2>/dev/null)" || return 1
    echo "$xml" | grep -qE "<model[^>]*>(qemu64|Penryn)</model>" || return 1
    echo "$xml" | grep -qE "name='svm'[^>]*policy='require'" && return 1
    return 0
}
HW6_HOSTS_MARK_BEGIN="# BEGIN HW6 CLUSTER"
HW6_HOSTS_MARK_END="# END HW6 CLUSTER"
HW6_CLUSTER_HOSTS=(servera serverb serverc)

HOST_A_IP=""
HOST_B_IP=""
HOST_C_IP=""
HOST_A_D=""
HOST_B_D=""
HOST_C_D=""

# Callbacks set by setup_*.sh
ok_cb()  { echo "  OK: $*"; }
warn_cb() { echo "  WARN: $*"; }

hw6_require_root() {
    if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
        echo "ERROR: Run as root:  sudo bash $0"
        exit 1
    fi
}

hw6_ip_from_d() {
    echo "${HW6_NETWORK_PREFIX}.$1"
}

hw6_validate_d() {
    local d="$1"
    [[ "$d" =~ ^[0-9]+$ ]] || return 1
    (( d >= 1 && d <= 254 )) || return 1
    return 0
}

hw6_prompt_d() {
    local label="$1"
    local varname="$2"
    local value=""

    while true; do
        read -r -p "  ${label} last octet (1-254, network ${HW6_NETWORK_PREFIX}.?): " value
        value="${value// /}"
        if hw6_validate_d "$value"; then
            printf -v "$varname" '%s' "$value"
            return 0
        fi
        echo "    Invalid: enter a number from 1 to 254."
    done
}

hw6_prompt_cluster_config() {
    echo ""
    echo "  Cluster IPs use fixed prefix: ${HW6_NETWORK_PREFIX}.<D>"
    echo "  Enter the last octet (D) for each host (no defaults)."
    echo ""

    hw6_prompt_d "Host-A (servera)" HOST_A_D
    hw6_prompt_d "Host-B (serverb)" HOST_B_D
    hw6_prompt_d "Host-C (serverc)" HOST_C_D

    if [[ "$HOST_A_D" == "$HOST_B_D" || "$HOST_A_D" == "$HOST_C_D" || "$HOST_B_D" == "$HOST_C_D" ]]; then
        echo "  Error: Host-A, B, and C must use different last octets."
        return 1
    fi

    HOST_A_IP="$(hw6_ip_from_d "$HOST_A_D")"
    HOST_B_IP="$(hw6_ip_from_d "$HOST_B_D")"
    HOST_C_IP="$(hw6_ip_from_d "$HOST_C_D")"
    return 0
}

hw6_write_config() {
    mkdir -p "$HW6_CONFIG_DIR"
    mkdir -p "$(dirname "$HW6_NFS_CONFIG_PATH")"
    mkdir -p "$HW6_NFS_KEYS_DIR"

    cat > "$HW6_CONFIG_FILE" << EOF
# HW6 cluster configuration (generated by setup)
NETWORK_PREFIX=${HW6_NETWORK_PREFIX}
SUBNET=${HW6_SUBNET}
HOST_A_IP=${HOST_A_IP}
HOST_B_IP=${HOST_B_IP}
HOST_C_IP=${HOST_C_IP}
HOST_A_D=${HOST_A_D}
HOST_B_D=${HOST_B_D}
HOST_C_D=${HOST_C_D}
NFS_DIR=${HW6_NFS_DIR}
CPU_CAP=${HW6_CPU_CAP}
MEM_CAP_MB=${HW6_MEM_CAP_MB}
HOST_DOMAIN=${HW6_HOST_DOMAIN}
EOF

    chmod 644 "$HW6_CONFIG_FILE"

    if [[ -d "$HW6_NFS_DIR" ]]; then
        cp -f "$HW6_CONFIG_FILE" "$HW6_NFS_CONFIG_PATH"
        chmod 644 "$HW6_NFS_CONFIG_PATH"
    fi
}

hw6_load_config() {
    local file="$1"
    [[ -f "$file" ]] || return 1
    # shellcheck disable=SC1090
    source "$file"
    [[ -n "${HOST_DOMAIN:-}" ]] && HW6_HOST_DOMAIN="$HOST_DOMAIN"
    [[ -n "$HOST_A_IP" && -n "$HOST_B_IP" && -n "$HOST_C_IP" ]] || return 1
    return 0
}

hw6_migrate_dest_uri() {
    echo "qemu+ssh://root@$(hw6_fqdn "$1")/system"
}

hw6_ensure_config() {
    local mode="${1:-prompt}"

    if [[ -f "$HW6_CONFIG_FILE" ]] && hw6_load_config "$HW6_CONFIG_FILE"; then
        echo ""
        echo "  Existing config: $HW6_CONFIG_FILE"
        echo "    Host-A (servera): $HOST_A_IP"
        echo "    Host-B (serverb): $HOST_B_IP"
        echo "    Host-C (serverc): $HOST_C_IP"
        echo ""
        read -r -p "  Use this config? [Y/n] " reuse
        if [[ ! "$reuse" =~ ^[Nn]$ ]]; then
            return 0
        fi
    fi

    if [[ "$mode" == "load_only" ]]; then
        return 1
    fi

    while true; do
        hw6_prompt_cluster_config || continue
        echo ""
        echo "  Summary:"
        echo "    Host-A (servera): $HOST_A_IP"
        echo "    Host-B (serverb): $HOST_B_IP"
        echo "    Host-C (serverc): $HOST_C_IP"
        echo "    Subnet (NFS):     $HW6_SUBNET"
        echo ""
        read -r -p "  Write config and continue? [y/N] " confirm
        if [[ "$confirm" =~ ^[Yy]$ ]]; then
            hw6_write_config
            return 0
        fi
        echo "  Re-enter host addresses."
    done
}

hw6_ensure_config_from_nfs() {
    if [[ -f "$HW6_CONFIG_FILE" ]] && hw6_load_config "$HW6_CONFIG_FILE"; then
        return 0
    fi
    if [[ -f "$HW6_NFS_CONFIG_PATH" ]] && hw6_load_config "$HW6_NFS_CONFIG_PATH"; then
        hw6_write_config
        return 0
    fi
    return 1
}

hw6_fqdn() {
    echo "${1}.${HW6_HOST_DOMAIN}"
}

hw6_cluster_ip_for_short() {
    case "$1" in
        servera) echo "$HOST_A_IP" ;;
        serverb) echo "$HOST_B_IP" ;;
        serverc) echo "$HOST_C_IP" ;;
        *) return 1 ;;
    esac
}

# Migration uses 192.168.0.x only — avoid getent returning IPv6 first
hw6_resolve_ipv4() {
    local name="${1:-$(hostname -f)}"
    local ip=""

    ip="$(getent ahostsv4 "$name" 2>/dev/null | awk '$2 == "STREAM" { print $1; exit }')"
    if [[ -z "$ip" ]]; then
        ip="$(getent hosts "$name" 2>/dev/null \
            | awk '/^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/ { print $1; exit }')"
    fi
    [[ -n "$ip" ]] && echo "$ip"
}

hw6_prefer_ipv4_gai() {
    local gai="/etc/gai.conf"
    touch "$gai"
    if grep -q 'BEGIN HW6' "$gai" 2>/dev/null; then
        return 0
    fi
    cat >> "$gai" << 'EOF'

# BEGIN HW6 — prefer IPv4 for libvirt / getent (lab uses 192.168.0.0/24)
precedence ::ffff:0:0/96  100
# END HW6
EOF
}

# QEMU advertises this address for incoming migration (avoids wrong NIC / localhost on C)
hw6_configure_libvirt_migration() {
    local ip="$1"
    local qconf="/etc/libvirt/qemu.conf"

    [[ -f "$qconf" ]] || { warn_cb "qemu.conf missing — skip migration_host"; return 0; }

    if grep -qE '^#?migration_host' "$qconf"; then
        sed -i "s|^#\\?migration_host.*|migration_host = \"${ip}\"|" "$qconf"
    else
        printf '\nmigration_host = "%s"\n' "$ip" >> "$qconf"
    fi

    systemctl try-restart libvirtd 2>/dev/null || systemctl restart libvirtd
    ok_cb "libvirt migration_host=${ip}"
}

# Fix hostname, /etc/hosts HW6 block, migration_host on B/C from Host-A (C often still dclab/localhost)
hw6_remote_repair_migration_target() {
    local short="$1"
    local fqdn ip

    fqdn="$(hw6_fqdn "$short")"
    ip="$(hw6_cluster_ip_for_short "$short")" || return 1
    hw6_ssh_test_host "$short" || return 1

    ssh -o BatchMode=yes -o ConnectTimeout=20 "root@${short}" bash -s -- \
        "$fqdn" "$ip" "$HW6_HOST_DOMAIN" "$HOST_A_IP" "$HOST_B_IP" "$HOST_C_IP" <<'EOS' || return 1
set -e
fqdn="$1"
myip="$2"
dom="$3"
aip="$4"
bip="$5"
cip="$6"
hf="/etc/hosts"
mb="# BEGIN HW6 CLUSTER"
me="# END HW6 CLUSTER"

hostnamectl set-hostname "$fqdn"
sed -i 's/^127\.0\.0\.1.*/127.0.0.1   localhost localhost.localdomain localhost4/' "$hf"
sed -i 's/^::1.*/::1         localhost localhost.localdomain localhost6/' "$hf"

tmp="$(mktemp)"
if grep -qF "$mb" "$hf" 2>/dev/null; then
    awk -v b="$mb" -v e="$me" '$0==b{skip=1} $0==e{skip=0;next} !skip{print}' "$hf" > "$tmp"
else
    cp "$hf" "$tmp"
fi
{
    cat "$tmp"
    echo ""
    echo "$mb"
    printf '%s\t%s %s\n' "$aip" "servera.${dom}" "servera"
    printf '%s\t%s %s\n' "$bip" "serverb.${dom}" "serverb"
    printf '%s\t%s %s\n' "$cip" "serverc.${dom}" "serverc"
    echo "$me"
} > "${tmp}.new"
install -m 644 "${tmp}.new" "$hf"
rm -f "$tmp" "${tmp}.new"

gai="/etc/gai.conf"
touch "$gai"
if ! grep -q 'BEGIN HW6' "$gai" 2>/dev/null; then
    cat >> "$gai" << 'GAIE'

# BEGIN HW6 — prefer IPv4 for libvirt / getent (lab uses 192.168.0.0/24)
precedence ::ffff:0:0/96  100
# END HW6
GAIE
fi

qconf="/etc/libvirt/qemu.conf"
[[ -f "$qconf" ]] || exit 1
if grep -qE '^#?migration_host' "$qconf"; then
    sed -i "s|^#\\?migration_host.*|migration_host = \"${myip}\"|" "$qconf"
else
    printf '\nmigration_host = "%s"\n' "$myip" >> "$qconf"
fi
systemctl try-restart libvirtd 2>/dev/null || systemctl restart libvirtd

resolved="$(getent ahostsv4 "$(hostname -f)" 2>/dev/null | awk '$2 == "STREAM" { print $1; exit }')"
if [[ -z "$resolved" ]]; then
    resolved="$(getent hosts "$(hostname -f)" | awk '/^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/ { print $1; exit }')"
fi
if [[ -z "$resolved" || "$resolved" == "127.0.0.1" || "$resolved" != "$myip" ]]; then
    echo "hostname broken (need IPv4 ${myip}): $(hostname -f) -> ${resolved:-?}"
    exit 1
fi
EOS
    ok_cb "Repaired ${short}: ${fqdn} -> ${ip}"
    return 0
}

hw6_migration_clear_dest_domain() {
    local vm="$1"
    local short="$2"
    hw6_ssh_test_host "$short" || return 0
    ssh -o BatchMode=yes "root@${short}" \
        "virsh destroy '${vm}' 2>/dev/null; virsh undefine '${vm}' --nvram 2>/dev/null; true" \
        2>/dev/null || true
}

# 127.0.0.1 must not map the cluster hostname (breaks live migration on libvirt 9+)
hw6_fix_loopback_hosts() {
    local hf="/etc/hosts"
    if grep -q '^127\.0\.0\.1' "$hf"; then
        sed -i 's/^127\.0\.0\.1.*/127.0.0.1   localhost localhost.localdomain localhost4/' "$hf"
    else
        echo '127.0.0.1   localhost localhost.localdomain localhost4' >> "$hf"
    fi
    if grep -q '^::1' "$hf"; then
        sed -i 's/^::1.*/::1         localhost localhost.localdomain localhost6/' "$hf"
    else
        echo '::1         localhost localhost.localdomain localhost6' >> "$hf"
    fi
}

# Replace or inject managed /etc/hosts block (idempotent, with FQDN)
hw6_hosts_inject() {
    local hf="/etc/hosts"
    local tmp
    local domain="${HW6_HOST_DOMAIN}"
    tmp="$(mktemp)"

    if grep -qF "$HW6_HOSTS_MARK_BEGIN" "$hf" 2>/dev/null; then
        awk -v b="$HW6_HOSTS_MARK_BEGIN" -v e="$HW6_HOSTS_MARK_END" '
            $0 == b { skip=1; next }
            $0 == e { skip=0; next }
            !skip { print }
        ' "$hf" > "$tmp"
    else
        cp "$hf" "$tmp"
    fi

    {
        cat "$tmp"
        echo ""
        echo "$HW6_HOSTS_MARK_BEGIN"
        printf '%s\t%s %s\n' "$HOST_A_IP" "servera.${domain}" "servera"
        printf '%s\t%s %s\n' "$HOST_B_IP" "serverb.${domain}" "serverb"
        printf '%s\t%s %s\n' "$HOST_C_IP" "serverc.${domain}" "serverc"
        echo "$HW6_HOSTS_MARK_END"
    } > "${tmp}.new"

    install -m 644 "${tmp}.new" "$hf"
    rm -f "$tmp" "${tmp}.new"
    ok_cb "/etc/hosts updated (FQDN *.${domain})"
}

# Set this machine's hostname + cluster /etc/hosts (required for virsh migrate)
hw6_configure_cluster_hostname() {
    local short="$1"
    local fqdn

    case "$short" in
        servera|serverb|serverc) ;;
        *) warn_cb "Unknown host role: $short"; return 1 ;;
    esac

    fqdn="$(hw6_fqdn "$short")"
    hostnamectl set-hostname "$fqdn" 2>/dev/null || echo "$fqdn" > /etc/hostname

    hw6_fix_loopback_hosts
    hw6_hosts_inject
    hw6_prefer_ipv4_gai
    hw6_configure_libvirt_migration "$(hw6_cluster_ip_for_short "$short")"

    ok_cb "Hostname: $(hostname -f) → $(hw6_resolve_ipv4) (IPv4)"
}

hw6_update_hosts_file() {
    hw6_hosts_inject
}

# Auto-detect Host-B vs Host-C from configured IPs on this machine
hw6_detect_sub_role() {
    local ip
    THIS_ROLE=""
    THIS_IP=""

    for ip in $(hostname -I 2>/dev/null); do
        if [[ "$ip" == "$HOST_B_IP" ]]; then
            THIS_ROLE="b"
            THIS_IP="$HOST_B_IP"
            return 0
        fi
        if [[ "$ip" == "$HOST_C_IP" ]]; then
            THIS_ROLE="c"
            THIS_IP="$HOST_C_IP"
            return 0
        fi
    done
    return 1
}

hw6_prompt_sub_role() {
    echo ""
    echo "  Could not detect role from NIC addresses."
    echo "    b = Host-B (serverb) → ${HOST_B_IP}"
    echo "    c = Host-C (serverc) → ${HOST_C_IP}"
    echo ""
    while true; do
        read -r -p "  Enter b or c: " THIS_ROLE
        THIS_ROLE="${THIS_ROLE,,}"
        case "$THIS_ROLE" in
            b) THIS_IP="$HOST_B_IP"; return 0 ;;
            c) THIS_IP="$HOST_C_IP"; return 0 ;;
            *) echo "    Enter b or c." ;;
        esac
    done
}

hw6_role_to_hostname() {
    case "$1" in
        a|A|servera) echo "servera" ;;
        b|B|serverb) echo "serverb" ;;
        c|C|serverc) echo "serverc" ;;
        *) return 1 ;;
    esac
}

hw6_install_openssh() {
    if ! rpm -q openssh-server openssh-clients &>/dev/null; then
        dnf install -y -q openssh-server openssh-clients
    fi
    systemctl enable --now sshd &>/dev/null || systemctl enable --now sshd.service
    ok_cb "sshd enabled"
}

# cloud-init ISO: Rocky 9/10 often has xorriso, not genisoimage / bridge-utils
hw6_install_iso_creator() {
    if command -v xorriso &>/dev/null || command -v genisoimage &>/dev/null; then
        return 0
    fi
    if dnf install -y -q xorriso &>/dev/null; then
        ok_cb "xorriso installed (cloud-init ISO)"
        return 0
    fi
    if dnf install -y -q genisoimage &>/dev/null; then
        ok_cb "genisoimage installed (cloud-init ISO)"
        return 0
    fi
    warn_cb "Install ISO tool manually: dnf install -y xorriso"
    return 1
}

hw6_make_cidata_iso() {
    local iso_path="$1"
    local user_data_file="$2"
    local meta_data_file="$3"

    if command -v genisoimage &>/dev/null; then
        genisoimage -quiet -output "$iso_path" -volid cidata -joliet -rock \
            "$user_data_file" "$meta_data_file"
        return $?
    fi
    if command -v xorriso &>/dev/null; then
        xorriso -as mkisofs -quiet -output "$iso_path" -volid cidata -joliet -rock \
            "$user_data_file" "$meta_data_file"
        return $?
    fi
    return 1
}

# Remote checks before migrate (NFS + libvirtd + FQDN not localhost)
hw6_migration_preflight() {
    local short="$1"
    local fqdn ip path rc
    fqdn="$(hw6_fqdn "$short")"
    ip="$(hw6_cluster_ip_for_short "$short")"
    path="$HW6_NFS_DIR"

    if ! hw6_ssh_test_host "$short"; then
        warn_cb "SSH to ${short} (${fqdn}) failed — run setup_sub on B/C"
        return 1
    fi

    if [[ "$short" == "servera" ]]; then
        systemctl is-active --quiet nfs-server || { warn_cb "nfs-server not active on Host-A"; return 1; }
        exportfs -v 2>/dev/null | grep -q "${path}" || { warn_cb "NFS export missing for ${path}"; return 1; }
    else
        rc=0
        ssh -o BatchMode=yes -o ConnectTimeout=10 "root@${short}" bash -s -- "$path" "$ip" <<'EOS' || rc=$?
path="$1"
want_ip="$2"
systemctl is-active --quiet libvirtd || { echo "libvirtd not active"; exit 1; }
mount | grep -q " on ${path} " || mount | grep -q "${path}" || { echo "NFS not mounted at ${path}"; exit 1; }
test -w "${path}" || { echo "NFS path not writable: ${path}"; exit 1; }
resolved="$(getent ahostsv4 "$(hostname -f)" 2>/dev/null | awk '$2 == "STREAM" { print $1; exit }')"
[[ -z "$resolved" ]] && resolved="$(getent hosts "$(hostname -f)" | awk '/^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/ { print $1; exit }')"
[[ "$resolved" == "$want_ip" ]] || { echo "FQDN not IPv4 ${want_ip}: got ${resolved:-?}"; exit 1; }
EOS
        if [[ $rc -ne 0 ]]; then
            warn_cb "Preflight ${short} failed (NFS/libvirtd/IPv4 FQDN)"
            return 1
        fi
    fi

    hw6_remote_repair_migration_target "$short" || {
        warn_cb "Repair failed on ${short} — on that host: sudo bash setup_sub.sh"
        return 1
    }

    ok_cb "Preflight OK: ${short} (${ip})"
    return 0
}

# Rocky 10: host-model CPU on A vs different hardware on C → "Failed to set special registers"
hw6_virsh_set_cpu_migratable() {
    local vm="$1"
    local was_running=0 state

    virsh dominfo "$vm" &>/dev/null || return 0

    state="$(virsh domstate "$vm" 2>/dev/null || echo "")"
    if [[ "$state" == "running" ]]; then
        was_running=1
        virsh destroy "$vm" >/dev/null 2>&1 || return 1
    fi

    if command -v virt-xml &>/dev/null; then
        if virt-xml "$vm" --edit --cpu "$(hw6_vm_cpu_spec)" --confirm >/dev/null 2>&1; then
            ok_cb "${vm}: CPU → $(hw6_vm_cpu_spec) (Intel migratable)"
            [[ "$was_running" -eq 1 ]] && virsh start "$vm" >/dev/null 2>&1
            return 0
        fi
    fi

    warn_cb "${vm}: install virt-install (virt-xml) or recreate with --cpu $(hw6_vm_cpu_spec)"
    [[ "$was_running" -eq 1 ]] && virsh start "$vm" >/dev/null 2>&1
    return 1
}

hw6_ssh_set_cpu_migratable() {
    local host="$1"
    local vm="$2"
    local spec
    spec="$(hw6_vm_cpu_spec)"

    hw6_ssh_test_host "$host" || return 1
    ssh -o BatchMode=yes -o ConnectTimeout=10 "root@${host}" bash -s -- "$vm" "$spec" <<'EOS'
vm="$1"
model="$2"
virsh dominfo "$vm" &>/dev/null || exit 0
state="$(virsh domstate "$vm" 2>/dev/null)"
[[ "$state" == "running" ]] && virsh destroy "$vm" 2>/dev/null || true
command -v virt-xml &>/dev/null || exit 1
virt-xml "$vm" --edit --cpu "$model" --confirm
[[ "$state" == "running" ]] && virsh start "$vm" 2>/dev/null || true
EOS
}

# Fix CPU on one host (hw6_fix_vm_cpu.sh only — not used during create_vms)
hw6_ensure_vm_cpu_migratable() {
    local vm="$1"
    local h

    if virsh dominfo "$vm" &>/dev/null; then
        hw6_vm_cpu_ok "$vm" && return 0
        hw6_virsh_set_cpu_migratable "$vm"
        return $?
    fi
    for h in serverb serverc; do
        hw6_ssh_test_host "$h" || continue
        ssh -o BatchMode=yes -o ConnectTimeout=8 "root@${h}" "virsh dominfo '${vm}'" &>/dev/null || continue
        if ssh -o BatchMode=yes -o ConnectTimeout=8 "root@${h}" "virsh dumpxml '${vm}'" 2>/dev/null \
            | grep -qE '<model[^>]*>(qemu64|Penryn)</model>'; then
            ok_cb "${vm}: CPU OK on ${h}"
            return 0
        fi
        hw6_ssh_set_cpu_migratable "$h" "$vm" && ok_cb "${vm}: CPU fixed on ${h}"
        return $?
    done
    warn_cb "${vm}: not defined on servera/b/c"
    return 1
}

hw6_ensure_all_vms_cpu_migratable() {
    local vm
    for vm in vm-1 vm-2 vm-3 vm-4 vm-5 vm-6; do
        hw6_ensure_vm_cpu_migratable "$vm" || true
    done
}

# Live migration (NFS shared qcow2 at /var/lib/libvirt/images on all hosts).
# libvirt 9+ may not treat NFS file disks as "shared" — --unsafe is required for this lab.
# dest_short: serverb|serverc — sets --migrateuri tcp://<cluster-ip>:0 for the data channel.
hw6_virsh_migrate_live() {
    local vm_name="$1"
    local _dest_uri_ignored="$2"
    local dest_short="${3:-}"
    local dest_ip=""
    local dest_uri=""
    local base=(--live --persistent --undefinesource --unsafe)

    [[ -n "$dest_short" ]] || { warn_cb "hw6_virsh_migrate_live: need dest_short (serverb|serverc)"; return 1; }

    dest_ip="$(hw6_cluster_ip_for_short "$dest_short")" || return 1
    dest_uri="$(hw6_migrate_dest_uri "$dest_short")"

    hw6_remote_repair_migration_target "$dest_short" || return 1
    hw6_migration_clear_dest_domain "$vm_name" "$dest_short"

    if virsh dominfo "$vm_name" &>/dev/null && ! hw6_vm_cpu_ok "$vm_name"; then
        warn_cb "${vm_name}: CPU not $(hw6_vm_cpu_spec) — run: sudo bash hw6_fix_vm_cpu.sh (or recreate with create_vms.sh)"
        return 1
    fi

    if ! virsh -c "$dest_uri" version &>/dev/null; then
        warn_cb "Cannot connect to ${dest_uri} — check SSH and libvirtd on ${dest_short}"
        return 1
    fi

    # FQDN in dest URI + cluster IP for RAM channel (avoids localhost / dclab on C)
    if virsh migrate "${base[@]}" --migrateuri "tcp://${dest_ip}:0" \
        "$vm_name" "$dest_uri"; then
        return 0
    fi

    warn_cb "${vm_name}: retry --tunnelled --p2p (no qemu+tcp / --p2p-only — unsupported on Rocky 10)"
    virsh migrate "${base[@]}" --tunnelled --p2p "$vm_name" "$dest_uri"
}

hw6_check_nfs_shared_storage() {
    local path="${1:-$HW6_NFS_DIR}"
    mount | grep -q " on ${path} " && return 0
    mount | grep -q "${path}" && return 0
    return 1
}

# Remove VM definition on this host and on B/C (after migration) + disk on NFS
hw6_cluster_undefine_vm() {
    local vm="$1"
    local images_dir="${2:-$HW6_NFS_DIR}"
    local disk="${images_dir}/${vm}.qcow2"
    local iso_nfs="${images_dir}/cloud-init-${vm}.iso"
    local iso_local="${HW6_CLOUD_INIT_DIR}/cloud-init-${vm}.iso"

    virsh destroy "$vm" 2>/dev/null || true
    virsh undefine "$vm" --nvram 2>/dev/null || true
    virsh undefine "$vm" --remove-all-storage 2>/dev/null || true

    for peer in serverb serverc; do
        hw6_ssh_test_host "$peer" || continue
        ssh -o BatchMode=yes -o ConnectTimeout=10 "root@${peer}" \
            "virsh destroy '${vm}' 2>/dev/null; virsh undefine '${vm}' --nvram 2>/dev/null; true" \
            2>/dev/null || true
    done

    rm -f "$disk" "$iso_nfs" "$iso_local"
}

# Drop cloud-init CDROM from persistent XML (ISO was only needed for first boot)
hw6_vm_detach_cloud_init_cdrom() {
    local vm="$1"
    local target was_running=0

    if virsh domstate "$vm" 2>/dev/null | grep -q running; then
        was_running=1
        virsh destroy "$vm" >/dev/null 2>&1 || true
    fi

    target="$(virsh domblklist "$vm" --details 2>/dev/null \
        | awk '$3 == "cdrom" && $4 == "raw" { print $1; exit }')"
    if [[ -z "$target" ]]; then
        target="$(virsh domblklist "$vm" 2>/dev/null \
            | awk '$2 ~ /\.iso$/ { print $1; exit }')"
    fi
    [[ -n "$target" ]] || return 0

    virsh detach-disk "$vm" "$target" --config 2>/dev/null \
        || virsh change-media "$vm" "$target" --eject --config 2>/dev/null \
        || true

    if [[ "$was_running" -eq 1 ]]; then
        virsh start "$vm" >/dev/null 2>&1 || true
    fi
}

hw6_sshd_lab_config() {
    local dropin="/etc/ssh/sshd_config.d/99-hw6-lab.conf"
    cat > "$dropin" << 'EOF'
# HW6 lab — root SSH for KVM live migration orchestration
PermitRootLogin yes
PubkeyAuthentication yes
PasswordAuthentication yes
EOF
    chmod 644 "$dropin"
    systemctl reload sshd 2>/dev/null || systemctl restart sshd
    ok_cb "sshd lab config applied"
}

hw6_ssh_client_config() {
    local dropin="/etc/ssh/ssh_config.d/50-hw6-cluster.conf"
    mkdir -p "$HW6_CONFIG_DIR"
    touch "$HW6_SSH_KNOWN_HOSTS"
    chmod 644 "$HW6_SSH_KNOWN_HOSTS"

    cat > "$dropin" << EOF
# HW6 cluster SSH client defaults
Host servera serverb serverc servera.${HW6_HOST_DOMAIN} serverb.${HW6_HOST_DOMAIN} serverc.${HW6_HOST_DOMAIN} ${HOST_A_IP} ${HOST_B_IP} ${HOST_C_IP}
    User root
    StrictHostKeyChecking accept-new
    UserKnownHostsFile ${HW6_SSH_KNOWN_HOSTS}
    GlobalKnownHostsFile /dev/null
    ServerAliveInterval 10
    ServerAliveCountMax 6
EOF
    chmod 644 "$dropin"
}

hw6_ssh_prepare() {
    local ssh_dir="/root/.ssh"

    mkdir -p "$ssh_dir" "$HW6_NFS_KEYS_DIR"
    chmod 700 "$ssh_dir"

    if [[ ! -f "${ssh_dir}/id_rsa" ]]; then
        ssh-keygen -t rsa -b 4096 -N "" -f "${ssh_dir}/id_rsa" -q
        ok_cb "SSH key pair generated"
    else
        ok_cb "SSH key pair present"
    fi

    touch "${ssh_dir}/authorized_keys"
    chmod 600 "${ssh_dir}/authorized_keys"

    if ! grep -qF "$(cat "${ssh_dir}/id_rsa.pub")" "${ssh_dir}/authorized_keys" 2>/dev/null; then
        cat "${ssh_dir}/id_rsa.pub" >> "${ssh_dir}/authorized_keys"
    fi

    hw6_ssh_client_config
    hw6_sshd_lab_config
}

hw6_ssh_append_pubkey() {
    local pub_file="$1"
    local auth="/root/.ssh/authorized_keys"
    [[ -f "$pub_file" ]] || return 0
    if ! grep -qF "$(cat "$pub_file")" "$auth" 2>/dev/null; then
        cat "$pub_file" >> "$auth"
    fi
}

hw6_ssh_publish_key() {
    local hostname="$1"
    local pub="/root/.ssh/id_rsa.pub"
    local dest="${HW6_NFS_KEYS_DIR}/${hostname}.pub"

    [[ -f "$pub" ]] || return 1
    mkdir -p "$HW6_NFS_KEYS_DIR"
    install -m 644 "$pub" "$dest"
    ok_cb "Published ${hostname}.pub on NFS"
}

hw6_ssh_sync_keys_from_nfs() {
    local pub auth="/root/.ssh/authorized_keys"

    hw6_ssh_append_pubkey "/root/.ssh/id_rsa.pub"

    if [[ ! -d "$HW6_NFS_KEYS_DIR" ]]; then
        warn_cb "NFS keys dir missing: ${HW6_NFS_KEYS_DIR}"
        return 1
    fi

    shopt -s nullglob
    for pub in "${HW6_NFS_KEYS_DIR}"/*.pub; do
        hw6_ssh_append_pubkey "$pub"
    done
    shopt -u nullglob

    chmod 600 "$auth"
    ok_cb "Merged cluster public keys into authorized_keys"
}

hw6_ssh_update_known_hosts() {
    mkdir -p "$HW6_CONFIG_DIR"
    : > "$HW6_SSH_KNOWN_HOSTS"

    # libvirt qemu+ssh URIs use FQDNs (servera.${HW6_HOST_DOMAIN}), so the
    # FQDN host keys MUST be in this file too — otherwise migrations from
    # B/C fail at completion with "Permission denied" because the inner
    # SSH (BatchMode) can't verify the destination host key.
    ssh-keyscan -t rsa,ecdsa,ed25519 \
        servera serverb serverc \
        "servera.${HW6_HOST_DOMAIN}" \
        "serverb.${HW6_HOST_DOMAIN}" \
        "serverc.${HW6_HOST_DOMAIN}" \
        "$HOST_A_IP" "$HOST_B_IP" "$HOST_C_IP" 2>/dev/null \
        >> "$HW6_SSH_KNOWN_HOSTS" || true

    # dedup
    sort -u "$HW6_SSH_KNOWN_HOSTS" -o "$HW6_SSH_KNOWN_HOSTS"
    chmod 644 "$HW6_SSH_KNOWN_HOSTS"
    ok_cb "ssh_known_hosts updated (short + FQDN + IP)"
}

hw6_ssh_wait_for_port() {
    local host="$1"
    local port="${2:-22}"
    local timeout="${3:-120}"
    local elapsed=0

    while (( elapsed < timeout )); do
        if timeout 2 bash -c "echo >/dev/tcp/${host}/${port}" 2>/dev/null; then
            return 0
        fi
        sleep 3
        elapsed=$((elapsed + 3))
    done
    return 1
}

hw6_ssh_test_host() {
    local host="$1"
    ssh -o BatchMode=yes -o ConnectTimeout=8 \
        "root@${host}" "virsh version" &>/dev/null
}

hw6_ssh_try_password_install() {
    local target_host="$1"
    local password="${HW6_ROOT_PASSWORD:-}"

    [[ -n "$password" ]] || return 1

    if ! command -v sshpass &>/dev/null; then
        dnf install -y -q sshpass 2>/dev/null || return 1
    fi

    sshpass -p "$password" ssh-copy-id -o StrictHostKeyChecking=accept-new \
        -i /root/.ssh/id_rsa.pub "root@${target_host}" &>/dev/null
}

hw6_ssh_setup_sub() {
    local role_hostname="$1"

    hw6_install_openssh
    hw6_ssh_prepare
    hw6_ssh_publish_key "$role_hostname"
    hw6_ssh_sync_keys_from_nfs
    hw6_ssh_update_known_hosts
}

hw6_ssh_wait_for_nfs_keys() {
    local need=("$@")
    local timeout="${HW6_SSH_WAIT_TIMEOUT:-300}"
    local elapsed=0
    local missing key

    while (( elapsed < timeout )); do
        missing=()
        for key in "${need[@]}"; do
            [[ -f "${HW6_NFS_KEYS_DIR}/${key}.pub" ]] || missing+=("$key")
        done
        if ((${#missing[@]} == 0)); then
            return 0
        fi
        echo "  Waiting for NFS keys: $(printf '%s.pub ' "${missing[@]}")(${elapsed}s / ${timeout}s)"
        echo "  → Run setup_sub.sh on the missing host(s)."
        sleep 5
        elapsed=$((elapsed + 5))
    done
    return 1
}

hw6_ssh_setup_main_peers() {
  hw6_ssh_sync_keys_from_nfs
  hw6_ssh_update_known_hosts

  local peer host

  for peer in serverb serverc; do
      host="$peer"
      if ! hw6_ssh_wait_for_port "$host" 22 30; then
          warn_cb "SSH port not open on ${host} — skip test"
          continue
      fi
      if hw6_ssh_test_host "$host"; then
          ok_cb "Passwordless SSH to ${host} OK"
      else
          if hw6_ssh_try_password_install "$host"; then
              ok_cb "Installed key on ${host} via HW6_ROOT_PASSWORD"
          else
              warn_cb "Cannot SSH to ${host} yet — finish setup_sub or set HW6_ROOT_PASSWORD"
          fi
      fi
  done
}

hw6_ssh_setup_main_finalize() {
    hw6_install_openssh
    hw6_ssh_prepare
    hw6_ssh_publish_key "servera"

    if [[ "${HW6_SKIP_SSH_WAIT:-0}" == "1" ]]; then
        warn_cb "HW6_SKIP_SSH_WAIT=1 — skipping wait for Host-B/C keys"
        hw6_ssh_setup_main_peers
        return 0
    fi

    echo ""
    echo "  Waiting for Host-B/C to publish SSH keys (setup_sub.sh)..."
    if hw6_ssh_wait_for_nfs_keys serverb serverc; then
        hw6_ssh_setup_main_peers
    else
        warn_cb "Timed out — run on Host-A after B/C setup:"
        warn_cb "  hw6_ssh_sync_keys_from_nfs && hw6_ssh_update_known_hosts"
        warn_cb "Or re-run: bash setup_main.sh (use existing config)"
    fi
}
